-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 12:21:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baseBlackboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseBlackboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseBlackboard` DEFAULT CHARACTER SET utf8 ;
USE `baseBlackboard` ;

-- -----------------------------------------------------
-- Table `baseBlackboard`.`registroUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboard`.`registroUsuarios` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(3) NOT NULL,
  `cedula` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` TEXT(20) NOT NULL,
  `tipoUsuario` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseBlackboard`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboard`.`profesor` (
  `codigo` INT NOT NULL,
  `areaEnfasis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fkRegistrosUsuariosProfesor`
    FOREIGN KEY (`codigo`)
    REFERENCES `baseBlackboard`.`registroUsuarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseBlackboard`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboard`.`Estudiante` (
  `codigo` INT NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `semestre` INT(2) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fkRegistroUsuarios`
    FOREIGN KEY (`codigo`)
    REFERENCES `baseBlackboard`.`registroUsuarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
