-- MySQL Script generated by MySQL Workbench
-- Mon Oct  7 18:21:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baseBlackboardc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseBlackboardc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseBlackboardc` DEFAULT CHARACTER SET utf8 ;
USE `baseBlackboardc` ;

-- -----------------------------------------------------
-- Table `baseBlackboardc`.`registrousuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboardc`.`registrousuarios` (
  `codigo` INT(11) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` INT(3) NOT NULL,
  `cedula` INT(11) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseBlackboardc`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboardc`.`Profesor` (
  `codigoProf` INT(11) NOT NULL,
  `areaEnfasis` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoProf`),
  CONSTRAINT `fkregistrousuariosProfesor`
    FOREIGN KEY (`codigoProf`)
    REFERENCES `baseBlackboardc`.`registrousuarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseBlackboardc`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboardc`.`Estudiante` (
  `codigoEst` INT(11) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `semestre` INT(2) NOT NULL,
  `AsistenteEnseñanza` TINYINT NOT NULL,
  PRIMARY KEY (`codigoEst`),
  UNIQUE INDEX `AsistenteEnseñanza_UNIQUE` (`AsistenteEnseñanza` ASC) VISIBLE,
  CONSTRAINT `fkregistrousuariosEstudiante`
    FOREIGN KEY (`codigoEst`)
    REFERENCES `baseBlackboardc`.`registrousuarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseBlackboardc`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboardc`.`Curso` (
  `codCurso` INT NOT NULL,
  `nomCurso` VARCHAR(45) NOT NULL,
  `directorCurso` VARCHAR(45) NOT NULL,
  `cantProfesores` INT NOT NULL,
  PRIMARY KEY (`codCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseBlackboardc`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseBlackboardc`.`Grupo` (
  `nrc` INT NOT NULL,
  `cantEst` INT NOT NULL,
  `codCurso` INT NOT NULL,
  `codigoProf` INT(11) NOT NULL,
  `codAsistenteEnseñanza` INT(11) NULL,
  PRIMARY KEY (`nrc`),
  INDEX `fkGrupoCurso_idx` (`codCurso` ASC) VISIBLE,
  INDEX `fk_Grupo_Profesor1_idx` (`codigoProf` ASC) VISIBLE,
  INDEX `fk_Grupo_Estudiante1_idx` (`codAsistenteEnseñanza` ASC) VISIBLE,
  CONSTRAINT `fkGrupoCurso`
    FOREIGN KEY (`codCurso`)
    REFERENCES `baseBlackboardc`.`Curso` (`codCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Profesor1`
    FOREIGN KEY (`codigoProf`)
    REFERENCES `baseBlackboardc`.`Profesor` (`codigoProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Estudiante1`
    FOREIGN KEY (`codAsistenteEnseñanza`)
    REFERENCES `baseBlackboardc`.`Estudiante` (`codigoEst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
